=== communitiesuk/epb-register-api/api/schemas/xml/SAP-Schema-19.0.0/SAP/ExternalDefinitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="EPC" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="EPC" attributeFormDefault="unqualified" version="EPC-1.4">
	<xs:annotation>
		<xs:documentation>
			This schema is used to provide 
				(a) the texts of recommendations on EPCs (by country)
				(b) addenda that may appear on RdSAP EPCs (same for all countries)
				(c) the options for Related Party Disclosure (same for all countries)
				(d) the options for Tenure (same for all countries)
				(e) the options for Transaction Type (by country)
		</xs:documentation>
	</xs:annotation>
	<xs:element name="ExternalDefinitions" type="ExternalDefinitions"/>
	<xs:complexType name="ExternalDefinitions">
		<xs:sequence>
			<xs:element name="Revision-Number" type="xs:string">
				<xs:annotation>
					<xs:documentation>The version number of the latest revision to any of the texts</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Revision-Date" type="xs:date">
				<xs:annotation>
					<xs:documentation>The date of the latest revision to any of the texts</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Country" type="Country" maxOccurs="3"/>
			<xs:element name="Addendum" type="Addendum" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Tenure" type="Tenure" minOccurs="0" maxOccurs="unbounded"></xs:element>
			<xs:element name="Related-Party-Disclosure" type="Related-Party-Disclosure" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>List of possible texts for Related Party Disclosure on EPCs</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Country">
		<xs:sequence>
			<xs:element name="Country-Code" type="UKCountryCode"/>
			<xs:element name="Average-SAP-Rating" type="EnergyRatingType">
				<xs:annotation>
					<xs:documentation>The average SAP rating for the country, to be shown on the EPC. If not used on the EPC, it may be 0</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Average-EI-Rating" type="EnergyRatingType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The average Environmental Impact rating for the country, to be shown on the EPC. If not used on the EPC, it may be 0 or omitted</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Recommendation" type="Recommendation" maxOccurs="unbounded"/>
			<xs:element name="Footnote-Text" type="Sentence" minOccurs="0" maxOccurs="2"/>
			<xs:element name="Transaction-Type" type="Transaction-Type" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Transaction types are given separately for each country since the list may differ</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Recommendation">
		<xs:sequence>
			<xs:element name="Improvement-Number" type="xs:positiveInteger">
				<xs:annotation>
					<xs:documentation>Recommendations are selected by recommendation number according to the criteria in Appendix T of the SAP specification.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Improvement-Summary" type="Sentence" maxOccurs="2">
				<xs:annotation>
					<xs:documentation>A short description of the improvement.  English only, or English and Welsh</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Improvement-Summary-2" type="Sentence" minOccurs="0" maxOccurs="2">
				<xs:annotation>
					<xs:documentation>A short description of the improvement.  English only, or English and Welsh</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Improvement-Heading" type="Sentence" maxOccurs="2">
				<xs:annotation>
					<xs:documentation>Text to precede the improvement description. English only, or English and Welsh</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Improvement-Description" type="Sentence" maxOccurs="2">
				<xs:annotation>
					<xs:documentation>Detailed description of the improvement.  English only, or English and Welsh</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Has-Footnote" type="xs:boolean" default="false" minOccurs="0">
				<xs:annotation>
					<xs:documentation>If true the Footnote-Text appears at the bottom of the page.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Addendum">
		<xs:annotation>
			<xs:documentation>Addendum-Number is unique for the text concerned. If an addendum is deleted the number will not be re-used.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Addendum-Number" type="xs:positiveInteger">
				<xs:annotation>
					<xs:documentation>The text of an addendum is picked up via the Addendum-Number.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Circumstances" type="xs:string">
				<xs:annotation>
					<xs:documentation>The circumstances under which this addendum should be included.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Addendum-Text" type="Sentence" minOccurs="2" maxOccurs="2">
				<xs:annotation>
					<xs:documentation>Text to be included on the EPC (English and Welsh versions).</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Tenure">
		<xs:sequence>
			<xs:element name="Tenure-Code" type="TenureCode"></xs:element>
			<xs:element name="Tenure-Text" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="TenureCode">
		<xs:annotation>
			<xs:documentation>TenureCode = 0 (unknown) is applicable only in the case of a new dwelling for which the intended tenure in not known. It is not to be used for an existing dwelling</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Owner-occupied</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Rented (social)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Rented (private)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="ND">
				<xs:annotation>
					<xs:documentation>Not defined - use in the case of a new dwelling for which the intended tenure in not known. It is not to be used for an existing dwelling</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Related-Party-Disclosure">
		<xs:annotation>
			<xs:documentation>List of possible texts for Related Party Disclosure on EPCs</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Disclosure-Code" type="xs:positiveInteger"/>
			<xs:element name="Disclosure-Text" type="Sentence" minOccurs="2" maxOccurs="2"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Transaction-Type">
		<xs:annotation>
			<xs:documentation>List of possible Transaction Types for EPCs. The transaction type indicates the reason for creating the EPC</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Display-Order" type="xs:positiveInteger">
				<xs:annotation>
					<xs:documentation>Number indicating the order in which the transaction types are to be presented to a software user.  
						These numbers might not be consecutive. The transaction types are to be shown with the lowest display number first through to the highest shown last</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Transaction-Code" type="xs:positiveInteger">
				<xs:annotation>
					<xs:documentation>Code to be used for Transaction-Type in the lodgement XML</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Transaction-Text" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="In-RdSAP" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>If false, transaction type is to be omitted when RdSAP is being used</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="LanguageCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>English</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Welsh</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="UKCountryCode">
		<xs:annotation>
			<xs:documentation>Code which indicates the country within the UK, taken from BS 6879.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="EAW">
				<xs:annotation>
					<xs:documentation>England and Wales</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="SCT">
				<xs:annotation>
					<xs:documentation>Scotland</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="NIR">
				<xs:annotation>
					<xs:documentation>Northern Ireland</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Sentence" type="Sentence"/>
	<xs:complexType name="Sentence">
		<xs:annotation>
			<xs:documentation>String value with a language code for natural-language text.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="LanguageCode" use="required">
					<xs:annotation>
						<xs:documentation>Identifies the language that the sentence is recorded in.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="EnergyRatingType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== communitiesuk/epb-register-api/api/schemas/xml/SAP-Schema-NI-14.2/Messages/ExternalDefinitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--EPC Recommendations, RdSAP Addenda and Related Party Disclosure-->
<EPC:ExternalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="EPC ExternalDefinitions.xsd" xmlns:EPC="EPC">
  <Revision-Number>2.1a</Revision-Number>
  <Revision-Date>2010-03-09</Revision-Date>
  <Country>
    <Country-Code>EAW</Country-Code>
    <Recommendation>
      <Improvement-Number>1</Improvement-Number>
      <Improvement-Summary language="1">Insulate hot water cylinder with 80 mm jacket</Improvement-Summary>
      <Improvement-Summary language="2">Inswleiddio’r silindr dŵr poeth gyda siaced 80 mm</Improvement-Summary>
      <Improvement-Heading language="1">Hot water cylinder insulation</Improvement-Heading>
      <Improvement-Heading language="2">Inswleiddiad silindr dŵr poeth</Improvement-Heading>
      <Improvement-Description language="1">Installing an 80 mm thick cylinder jacket around the hot water cylinder will help to maintain the water at the required temperature; this will reduce the amount of energy used and lower fuel bills. A cylinder jacket is a layer of insulation that is fitted around the hot water cylinder. The jacket should be fitted over any thermostat clamped to the cylinder. Hot water pipes from the hot water cylinder should also be insulated, using pre-formed pipe insulation of up to 50 mm thickness, or to suit the space available, for as far as they can be accessed to reduce losses in summer. All these materials can be purchased from DIY stores and installed by a competent DIY enthusiast.</Improvement-Description>
      <Improvement-Description language="2">Bydd gosod siaced silindr o drwch 80 mm o amgylch y silindr dŵr poeth yn helpu i gadw’r dŵr ar y tymheredd gofynnol; bydd hyn yn gostwng y swm o ynni a ddefnyddir ac yn lleihau’r biliau tanwydd. Haenen inswleiddio sydd yn ffitio o amgylch y silindr dŵr poeth yw siaced silindr. Dylai’r siaced gael ei ffitio dros unrhyw thermostat sydd wedi ei glampio i’r silindr. Dylai’r pibellau dŵr poeth sydd yn dod o’r silindr gael eu hinswleiddio hefyd, trwy ddefnyddio inswleiddiad pibell sydd wedi ei ffurfio’n barod, o drwch hyd at 50 mm, neu sy’n addas ar gyfer y gofod sydd ar gael, am cyn belled ag y gellir gwneud hynny i leihau colledion yn yr haf. Gellir prynu’r holl ddeunydd yma mewn siopau DIY ac fe all unigolyn medrus â diddordeb brwd mewn DIY ei osod.</Improvement-Description>
    </Recommendation>
    <Recommendation>
      <Improvement-Number>2</Improvement-Number>
      <Improvement-Summary language="1">Increase hot water cylinder insulation</Improvement-Summary>
      <Improvement-Summary language="2">Cynyddu inswleiddiad dŵr poeth</Improvement-Summary>
      <Improvement-Heading language="1">Hot water cylinder insulation</Improvement-Heading>
      <Improvement-Heading language="2">Inswleiddiad silindr dŵr poeth</Improvement-Heading>
      <Improvement-Description language="1">Increasing the thickness of existing insulation around the hot water cylinder will help to maintain the water at the required temperature; this will reduce the amount of energy used and lower fuel bills. An additional cylinder jacket or other suitable insulation layer can be used. The insulation should be fitted over any thermostat clamped to the cylinder. Hot water pipes from the hot water cylinder should also be insulated, using pre-formed pipe insulation of up to 50 mm thickness, or to suit the space available, for as far as they can be accessed to reduce losses in summer. All these materials can be purchased from DIY stores and installed by a competent DIY enthusiast.</Improvement-Description>
      <Improvement-Description language="2">Bydd cynyddu trwch yr inswleiddiad presennol o amgylch y silindr dŵr poeth yn helpu i gadw’r dŵr ar y tymheredd gofynnol; bydd hyn yn gostwng y swm o ynni a ddefnyddir ac yn lleihau’r biliau tanwydd. Gall siaced silindr ychwanegol neu haen arall o inswleiddiad addas gael eu defnyddio. Dylai’r inswleiddiad gael ei ffitio dros unrhyw thermostat sydd wedi ei glampio i’r silindr. Dylai’r pibellau dŵr poeth sydd yn dod o’r silindr gael eu hinswleiddio hefyd, trwy ddefnyddio inswleiddiad pibell sydd wedi ei ffurfio’n barod, o drwch hyd at 50 mm, neu sy’n addas ar gyfer y gofod sydd ar gael, am cyn belled ag y gellir gwneud hynny i leihau colledion yn yr haf. Gellir prynu’r holl ddeunydd yma mewn siopau DIY ac fe all unigolyn medrus â diddordeb brwd mewn DIY ei osod.</Improvement-Description>
    </Recommendation>
    <Recommendation>
      <Improvement-Number>3</Improvement-Number>
      <Improvement-Summary language="1">Add additional 80 mm jacket to hot water cylinder</Improvement-Summary>
      <Improvement-Summary language="2">Ychwanegu siaced 80 mm ychwanegol i’r siaced dŵr poeth</Improvement-Summary>
      <Improvement-Heading language="1">Hot water cylinder insulation</Improvement-Heading>
      <Improvement-Heading language="2">Inswleiddiad silindr dŵr poeth</Improvement-Heading>
      <Improvement-Description language="1">Increasing the thickness of existing insulation by adding an 80 mm cylinder jacket around the hot water cylinder will help maintain the water at the required temperature; this will reduce the amount of energy used and lower fuel bills. The jacket should be fitted over the top of the existing foam insulation and over any thermostat clamped to the cylinder. Hot water pipes from the hot water cylinder should also be insulated, using pre-formed pipe insulation of up to 50 mm thickness, or to suit the space available, for as far as they can be accessed to reduce losses in summer. All these materials can be purchased from DIY stores and installed by a competent DIY enthusiast.</Improvement-Description>
      <Improvement-Description language="2">Bydd cynyddu trwch yr inswleiddiad presennol drwy ychwanegu siaced silindr 80 mm o drwch o amgylch y silindr dŵr poeth yn helpu i gadw’r dŵr ar y tymheredd gofynnol; bydd hyn yn gostwng y swm o ynni a ddefnyddir a lleihau’r biliau tanwydd. Dylai’r siaced gael ei ffitio dros yr inswleiddiad sbwng presennol a thros unrhyw thermostat sydd wedi ei glampio ar y silindr. Dylai’r pibellau dŵr poeth gael eu hinswleiddio hefyd, trwy ddefnyddio inswleiddiad pibell sydd wedi ei ffurfio’n barod o drwch hyd at 50 mm, neu sy’n addas ar gyfer y gofod sydd ar gael, am cyn belled ag y gellir gwneud hynny i leihau colledion yn yr haf. Gellir prynu’r holl ddeunydd yma mewn siop DIY ac fe all unigolyn medrus â diddordeb brwd mewn DIY ei osod.</Improvement-Description>
    </Recommendation>
    <Recommendation>
      <Improvement-Number>4</Improvement-Number>
      <Improvement-Summary language="1">Hot water cylinder thermostat</Improvement-Summary>
      <Improvement-Summary language="2">Thermostat silindr dŵr poeth</Improvement-Summary>
      <Improvement-Heading language="1">Cylinder thermostat</Improvement-Heading>
      <Improvement-Heading language="2">Thermostat silindr</Improvement-Heading>
      <Improvement-Description language="1">A hot water cylinder thermostat enables the boiler to switch off when the water in the cylinder reaches the required temperature; this minimises the amount of energy that is used and lowers fuel bills. The thermostat is a temperature sensor that sends a signal to the boiler when the required temperature is reached. To be fully effective it needs to be sited in the correct position and hard wired in place, so it should be installed by a competent plumber or heating engineer.</Improvement-Description>
      <Improvement-Description language="2">Mae thermostat silindr dŵr poeth yn galluogi’r bwyler i ddiffodd pan fydd y dŵr yn y silindr yn cyrraedd y tymheredd gofynnol; mae hyn yn minimeiddio’r swm o ynni sydd yn cael ei ddefnyddio ac yn gostwng biliau tanwydd. Y sensor tymheredd yw’r thermostat sydd yn danfon signal i’r bwyler pan fydd y tymheredd gofynnol wedi ei gyrraedd. I fod yn hollol effeithiol mae angen iddo gael ei leoli yn y safle cywir a’i wifro’n galed i’w le, felly dylai plymiwr neu beiriannydd gwresogi cymwys ei osod.</Improvement-Description>
    </Recommendation>
    <Recommendation>
      <Improvement-Number>5</Improvement-Number>
      <Improvement-Summary language="1">Increase loft insulation to 270 mm</Improvement-Summary>
      <Improvement-Summary language="2">Cynyddu inswleiddiad croglofft i 270 mm</Improvement-Summary>
      <Improvement-Heading language="1">Loft insulation</Improvement-Heading>
      <Improvement-Heading language="2">Inswleiddiad croglofft</Improvement-Heading>
      <Improvement-Description language="1">Loft insulation laid in the loft space or between roof rafters to a depth of at least 270 mm will significantly reduce heat loss through the roof; this will improve levels of comfort, reduce energy use and lower fuel bills. Insulation should not be placed below any cold water storage tank, any such tank should also be insulated on its sides and top, and there should be boarding on battens over the insulation to provide safe access between the loft hatch and the cold water tank. The insulation can be installed by professional contractors but also by a capable DIY enthusiast. Loose granules may be used instead of insulation quilt; this form of loft insulation can be blown into place and can be useful where access is difficult. The loft space must have adequate ventilation to prevent dampness; seek advice about this if unsure. Further information about loft insulation and details of local contractors can be obtained from the National Insulation Association (www.nationalinsulationassociation.org.uk).</Improvement-Description>
